export enum SCENES {
    START = 'START',
    MAIN_MENU = 'MAIN_MENU',

    // CREATE SCENES
    CREATE_TRAINING = 'CREATE_TRAINING',
    CREATE_EXERCISE = 'CREATE_EXERCISE',

    // EDIT SCENES
    EDIT_TRAINING = 'EDIT_TRAINING',

    // START TRAINING SCENES
    START_TRAINING = 'START_TRAINING',
}
